/*
Code taken from https://stackoverflow.com/a/15526256/5274680
 */
package WebService.Logic;

import java.io.UnsupportedEncodingException;
import java.util.Properties;
import java.util.Random;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.AddressException;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;

public class MailHandler {

    final private String username = "GroupTenSemesterProject@gmail.com";
    final private String password = "\"#q=P'3-K]g[)7H*";
    public String sendMailAutogenerated(String ID, String mailTo, String name, String CustomerPassword) {

        

        Properties props = new Properties();
        props.put("mail.smtp.starttls.enable", "true");
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.host", "smtp.gmail.com");
        props.put("mail.smtp.port", "587");

        Session session = Session.getInstance(props,
                new javax.mail.Authenticator() {
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(username, password);
            }
        });

        try {
            Message message = new MimeMessage(session);
            message.setFrom(new InternetAddress("GroupTenSemesterProject@gmail.com"));
            message.setRecipients(Message.RecipientType.TO,
                    InternetAddress.parse(mailTo));
            message.setSubject("Account info for Elena Banking");
            message.setText("Dear " + name + " here is your login information. It contains your unique ID which is used for login, as well as a random generated password.\n\n"
                    + "ID: " + ID.substring(1) + "\n" + "Password: " + CustomerPassword + "\n\nPlease change your password at the first posible obitunity" + "\n\n Best regards from Group 10");
            Transport.send(message);
        } catch (MessagingException e) {
            throw new RuntimeException(e);
        }
        return "Success";
    }

    public String sendResetPasswordAutogenerated(String ID, String mailTo, String name) {

        System.out.println("test3");
        String lower = "abcdefghijklmnopqrstuvwxyz";
        String digits = "0123456789";
        String specialSymbols = "!#¤%&/()=?@£$€{[]}";
        StringBuilder sb = new StringBuilder();
        int n = 10;
        String set = lower + lower.toUpperCase() + specialSymbols + digits; // characters to choose from

        for (int i = 0; i < n; i++) {
            int k = new Random().nextInt(set.length());
            sb.append(set.charAt(k));
        }
        String customerPassword = sb.toString();

        Properties props = new Properties();
        props.put("mail.smtp.starttls.enable", "true");
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.host", "smtp.gmail.com");
        props.put("mail.smtp.port", "587");
        System.out.println("test1");
        Session session = Session.getInstance(props,
                new javax.mail.Authenticator() {
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(username, password);
            }
        });

        try {
            Message message = new MimeMessage(session);
            System.out.println("test2");
            message.setFrom(new InternetAddress("GroupTenSemesterProject@gmail.com"));
            message.setRecipients(Message.RecipientType.TO,
                    InternetAddress.parse(mailTo));
            message.setSubject("Reset password");
            message.setText("Dear " + name +"\n\n"+ "Your password has been reset, if this was not your doing please contact your Bank of Elena representative." + " Here is your login information. It contains your unique ID which is used for login, as well as a random generated password.\n\n"
                    + "ID: " + ID.substring(1) + "\n" + "Password: " + customerPassword +"\n" + "Please change your password at the first posible opportunity." + "\n\nBest regards from Group 10");
            Transport.send(message);
        } catch (MessagingException e) {
            throw new RuntimeException(e);
        }
        return customerPassword;
    }

    
        public String contactBankMail(String ID, String subject, String text, String email){
        Properties props = new Properties();
        props.put("mail.smtp.starttls.enable", "true");
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.host", "smtp.gmail.com");
        props.put("mail.smtp.port", "587");

        Session session = Session.getInstance(props,
          new javax.mail.Authenticator() {
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(username, password);
            }
        });
        
        try {
            Message message = new MimeMessage(session);
            message.setFrom(new InternetAddress("GroupTenSemesterProject@gmail.com"));
            message.setRecipients(Message.RecipientType.TO,
            InternetAddress.parse("GroupTenSemesterProject@gmail.com"));
            message.setSubject(subject);
            message.setText("From: " + ID + "Email: " + email + "\n" + text);
            Transport.send(message);
        } catch (MessagingException e) {
            throw new RuntimeException(e);
        }
        
        try {
            Message message = new MimeMessage(session);
            message.setFrom(new InternetAddress("GroupTenSemesterProject@gmail.com"));
            message.setRecipients(Message.RecipientType.TO,
            InternetAddress.parse(email));
            message.setSubject("Bank contact");
            message.setText("We have recieved following information from you, we will respond as soon as possible" + "\n" + subject + "\n" + text);
            Transport.send(message);
        } catch (MessagingException e) {
            throw new RuntimeException(e);
        }
        return "Success";
    }
}

